spring.application.name=sistema-asistencia

# ===================================
# PUERTO
# ===================================

server.port=8080

# ===================================
# POSTGRESQL
# ===================================

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_asistencia
spring.datasource.username=postgres
spring.datasource.password=326383

# ===================================
# JPA / HIBERNATE
# ===================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================
# THYMELEAF
# ===================================

spring.thymeleaf.cache=false